# Generated by Django 4.1.3 on 2022-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='media/'),
        ),
    ]
